apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: gcr.io/upheld-setting-436613-s1/notes:latest
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: NODE_ENV
        - name: MONGODB_URI
          value: mongodb://mongo.prod.svc.cluster.local:27017/notesdb
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: notes
  namespace: prod
spec:
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort